include:
  - project: "mintel/gitlab-ci-templates/npm-packaging"
    ref: release-5.x
    file: "/templates/gitlab-ci-npm.template.yml"

variables:
  PACKAGE_MANAGER: "pnpm"
  RUN_VR_TEST: 0
  I18N_EXTRACT: 0
  AUDIT_COMMAND: "pnpm audit"
